- database/schema.sql
- src/main/java/com/sistema/gpon/Repository/ClienteRepository.java
- src/main/java/com/sistema/gpon/Repository/DistritoRepository.java
- src/main/java/com/sistema/gpon/Repository/PlanRepository.java
- src/main/java/com/sistema/gpon/Repository/PromocionRepository.java
- src/main/java/com/sistema/gpon/Repository/RegistroRUC10Repository.java
- src/main/java/com/sistema/gpon/Repository/RolRepository.java
- src/main/java/com/sistema/gpon/Repository/SectorRepository.java
- src/main/java/com/sistema/gpon/Repository/UsuarioRepository.java
- src/main/java/com/sistema/gpon/controller/MainController.java
- src/main/java/com/sistema/gpon/model/Cliente.java
- src/main/java/com/sistema/gpon/model/Distrito.java
- src/main/java/com/sistema/gpon/model/Estado.java
- src/main/java/com/sistema/gpon/model/Plan.java
- src/main/java/com/sistema/gpon/model/Promocion.java
- src/main/java/com/sistema/gpon/model/RegistroRUC10.java
- src/main/java/com/sistema/gpon/model/Rol.java
- src/main/java/com/sistema/gpon/model/Sector.java
- src/main/java/com/sistema/gpon/model/Usuario.java
- src/main/java/com/sistema/gpon/service/ClienteService.java
- src/main/java/com/sistema/gpon/service/impl/ClienteServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/DistritoServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/PlanServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/PromocionServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/RegistroRUC10ServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/RolServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/SectorServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/UsuarioServiceImpl.java
- src/main/resources/application.properties
Se hizo los cambios necesarios para que funcione , como encontrar Integer en clases , como errores de mapeos de tablas a clases , y la nueva tabla que se puso que es Estado
> last mistake fixed

- src/main/java/com/sistema/gpon/controller/PromocionController.java
- src/main/java/com/sistema/gpon/controller/UsuarioController.java
- src/main/java/com/sistema/gpon/repository/PromocionRepository.java
- src/main/java/com/sistema/gpon/repository/UsuarioRepository.java
- src/main/java/com/sistema/gpon/service/PromocionService.java
- src/main/java/com/sistema/gpon/service/UsuarioService.java
- src/main/java/com/sistema/gpon/service/impl/PromocionServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/UsuarioServiceImpl.java
- src/main/java/com/sistema/gpon/utils/Alert.java
- src/main/java/com/sistema/gpon/utils/ResultadoResponse.java
- src/main/resources/templates/main/index.html
- src/main/resources/templates/promociones/edicion.html
- src/main/resources/templates/promociones/index.html
- src/main/resources/templates/promociones/nuevo.html
"Agregando crud de Promociones, junto con sus vistas respectivas,agregando mensaje de confirmacion e informacion en insercion y actualizacion respectivamente" Me falta el tema de el crud de roles para avanzar en crear usuarios
> Crud y Vistas de Promociones

- src/main/java/com/sistema/gpon/controller/PlanController.java
- src/main/java/com/sistema/gpon/controller/RegistroRUC10Controller.java
- src/main/resources/application.properties
- src/main/resources/static/css/registroRUC10.css
- src/main/resources/templates/clientes/index.html
- src/main/resources/templates/distritos/index.html
- src/main/resources/templates/formGeneral/formGpon.html
- src/main/resources/templates/layout.html
- src/main/resources/templates/main/index.html
- src/main/resources/templates/planes/index.html
- src/main/resources/templates/roles/index.html
- src/main/resources/templates/sectores/index.html
- src/main/resources/templates/usuarios/index.html
Se hizo el cambio general con un layout para hacer responsivo a lo que es la pagina , y a las demas paginas les deje la estructura ya hecha para que solo diseñen y no tengan que hacer otros cambios .
> Uso de Layout

- src/main/java/com/sistema/gpon/DTO/RucDTO.java
- src/main/java/com/sistema/gpon/controller/RegistroRUC10Controller.java
- src/main/java/com/sistema/gpon/model/ContactoPrincipal.java
- src/main/java/com/sistema/gpon/model/ContactoSecundario.java
- src/main/java/com/sistema/gpon/model/Cronograma.java
- src/main/java/com/sistema/gpon/model/RegistroRUC10.java
- src/main/java/com/sistema/gpon/repository/ContactoPrimarioRepository.java
- src/main/java/com/sistema/gpon/repository/ContactoSecundarioRepository.java
- src/main/java/com/sistema/gpon/repository/CronogramaRepository.java
- src/main/java/com/sistema/gpon/service/ContactoPrincipalService.java
- src/main/java/com/sistema/gpon/service/ContactoSecundarioService.java
- src/main/java/com/sistema/gpon/service/CronogramaService.java
- src/main/java/com/sistema/gpon/service/DistritoService.java
- src/main/java/com/sistema/gpon/service/impl/ContactoPrincipalImpl.java
- src/main/java/com/sistema/gpon/service/impl/ContactoSecundarioImpl.java
- src/main/java/com/sistema/gpon/service/impl/CronogramaImpl.java
- src/main/java/com/sistema/gpon/service/impl/DistritoServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/SectorServiceImpl.java
- src/main/resources/templates/home/dashboard.html
- src/main/resources/templates/registros/index.html
mis avanzes de lo que es mi formulario , aun esta en proceso , no esta funcionando todavia pero el dia de mañana seguire avanzandolo , pero no molesta a los demas clases ni trabajos.
mañana lo terminare.
> avanze Formulario

- src/main/resources/templates/home/dashboard.html
- src/main/resources/templates/layout.html
- Updated route paths and names to align with new structure.
- Translated all dashboard labels, titles, and UI elements from English to Spanish for localization consistency.
- Verified that navigation works correctly after route updates.
> Adjust routes and translate dashboard content to Spanish

- src/main/resources/templates/cuenta/login.html
This PR cleans up the login view by removing unnecessary HTML tags and improving the indentation for better readability and maintainability.
> Remove unnecessary tags and improve indentation in login view

- pom.xml
- src/main/java/com/sistema/gpon/controller/ClienteController.java
- src/main/java/com/sistema/gpon/model/Cliente.java
- src/main/resources/static/css/index.css
- src/main/resources/templates/clientes/edicion.html
- src/main/resources/templates/clientes/nuevo.html
Added visual validation logic for 'create' and 'edit' client forms. Inputs and selects now remove 'is-invalid' class on user input or selection change.
> Add real-time input validation to client views

- database/data.sql
- database/schema.sql
- src/main/java/com/sistema/gpon/controller/PlanController.java
- src/main/java/com/sistema/gpon/model/Plan.java
- src/main/java/com/sistema/gpon/repository/PlanRepository.java
- src/main/java/com/sistema/gpon/service/PlanService.java
- src/main/java/com/sistema/gpon/service/impl/PlanServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/PromocionServiceImpl.java
- src/main/resources/application.properties
- src/main/resources/templates/planes/edicion.html
- src/main/resources/templates/planes/index.html
- src/main/resources/templates/planes/nuevo.html
> Crud Planes Finalizado

- src/main/java/com/sistema/gpon/controller/ClienteController.java
- src/main/java/com/sistema/gpon/controller/UsuarioController.java
- src/main/java/com/sistema/gpon/dto/ClienteFilter.java
- src/main/java/com/sistema/gpon/dto/RegistroFilter.java
- src/main/java/com/sistema/gpon/dto/UsuarioFilter.java
- src/main/java/com/sistema/gpon/repository/ClienteRepository.java
- src/main/java/com/sistema/gpon/service/ClienteService.java
- src/main/java/com/sistema/gpon/service/UsuarioService.java
- src/main/java/com/sistema/gpon/service/impl/ClienteServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/UsuarioServiceImpl.java
- src/main/resources/templates/clientes/index.html
This PR adds a dropdown filter to the Clientes view that allows users to filter clients by their active or inactive status.
> ✨ feat(clients): add active/inactive status filter to view

- src/main/resources/templates/usuarios/edicion.html
- src/main/resources/templates/usuarios/nuevo.html
Fixed and updated the User views by renaming the estado field to activo.
> 🐛 fix: updated User views to replace 'estado' field with 'activo'

- src/main/java/com/sistema/gpon/controller/RegistroRUC10Controller.java
- src/main/java/com/sistema/gpon/dto/UsuarioFilter.java
- src/main/java/com/sistema/gpon/repository/UsuarioRepository.java
- src/main/java/com/sistema/gpon/service/UsuarioService.java
- src/main/java/com/sistema/gpon/service/impl/UsuarioServiceImpl.java
- src/main/resources/templates/clientes/index.html
- src/main/resources/templates/planes/index.html
- src/main/resources/templates/promociones/index.html
- src/main/resources/templates/registros/index.html
- src/main/resources/templates/usuarios/index.html
- Added a new dropdown filter for 'active' status in the user listing view.
- Adjusted the filter form and export buttons layout using Bootstrap flex utilities to improve responsiveness across all screen sizes.
- Ensured elements no longer overlap or stack improperly on small screens while maintaining compact inline layout on desktop.
> ✨ feat: add 'active' filter and improve filter row responsiveness in user view

- src/main/java/com/sistema/gpon/controller/ClienteController.java
- src/main/java/com/sistema/gpon/controller/CuentaController.java
- src/main/java/com/sistema/gpon/controller/PlanController.java
- src/main/java/com/sistema/gpon/controller/PromocionController.java
- src/main/java/com/sistema/gpon/controller/RegistroRUC10Controller.java
- src/main/java/com/sistema/gpon/controller/UsuarioController.java
- src/main/java/com/sistema/gpon/service/ContactoPrincipalService.java
- src/main/java/com/sistema/gpon/service/ContactoSecundarioService.java
- src/main/java/com/sistema/gpon/service/CronogramaService.java
- src/main/java/com/sistema/gpon/service/DistritoService.java
- src/main/java/com/sistema/gpon/service/impl/ClienteServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/PlanServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/PromocionServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/UsuarioServiceImpl.java
- src/main/java/com/sistema/gpon/utils/Alert.java
- src/main/resources/templates/clientes/edicion.html
- src/main/resources/templates/clientes/index.html
- src/main/resources/templates/clientes/nuevo.html
- src/main/resources/templates/fragments/layout.html
- src/main/resources/templates/usuarios/edicion.html
**This update enhances the alerting system across the application:**
- Refined alert message texts for clarity and user-friendliness.
- Replaced basic alerts with SweetAlert modals for a more modern and consistent UI.
- Updated utility methods in Alert.java to support customized titles, icons, and dynamic messages.
- Ensured that all success/error messages reflect meaningful actions (e.g., activation, registration).
> ✨ feat/alerts: improve alert messages and switch to SweetAlert modals

- src/main/java/com/sistema/gpon/controller/PlanController.java
- src/main/java/com/sistema/gpon/controller/PromocionController.java
- src/main/java/com/sistema/gpon/controller/UsuarioController.java
- src/main/java/com/sistema/gpon/model/Plan.java
- src/main/java/com/sistema/gpon/model/Promocion.java
- src/main/java/com/sistema/gpon/model/Usuario.java
- src/main/java/com/sistema/gpon/service/impl/UsuarioServiceImpl.java
- src/main/resources/templates/planes/edicion.html
- src/main/resources/templates/planes/nuevo.html
- src/main/resources/templates/promociones/edicion.html
- src/main/resources/templates/promociones/nuevo.html
- src/main/resources/templates/usuarios/edicion.html
- src/main/resources/templates/usuarios/index.html
- src/main/resources/templates/usuarios/nuevo.html
This PR adds the missing form validation messages to the user registration and edit views. It ensures consistent display of error messages across all fields, particularly for name, surname, email, and role. This improves the user experience by providing immediate feedback on validation errors.
> ✨ feat: add missing validation messages to user views

- src/main/java/com/sistema/gpon/SistemaRegistroGponApplication.java
- src/main/java/com/sistema/gpon/config/SessionFilter.java
- src/main/java/com/sistema/gpon/controller/CuentaController.java
- src/main/java/com/sistema/gpon/service/UsuarioService.java
- src/main/java/com/sistema/gpon/service/impl/UsuarioServiceImpl.java
Adds a basic session filter to restrict access to authenticated users only.  
Redirects logged-in users away from login routes and unauthenticated users to the login page.
> 🔒 chore/security: add simple login session filter

- src/main/java/com/sistema/gpon/controller/CuentaController.java
- src/main/java/com/sistema/gpon/dto/UsuarioContrasenaDTO.java
- src/main/java/com/sistema/gpon/dto/UsuarioPerfilDTO.java
- src/main/resources/templates/cuenta/perfil.html
- src/main/resources/templates/usuarios/nuevo.html
- Separated profile view into two forms: personal info and password change.
- Improved styles and layout.
- Added show/hide password toggle.
> ✨ feat(profile): improve profile view functionality

- src/main/resources/templates/cuenta/perfil.html
- src/main/resources/templates/planes/index.html
- src/main/resources/templates/promociones/index.html
- Removed export to PDF/Excel buttons from Plans and Promotions views as they are no longer needed.
- Cleaned up related markup.
> 🔥 chore(ui): remove export buttons from plans and promotions views

- src/main/java/com/sistema/gpon/controller/RegistroRUC10Controller.java
- src/main/resources/static/css/index.css
- src/main/resources/templates/registros/nuevo.html
Custom styles were implemented for the stepper component in the RUC10 multi-step registration form. Steps are now displayed horizontally with a continuous connector line, centered icons, and dynamic colors based on progress (active/completed). This enhances user experience and provides a clearer visual flow for navigating the form.
> 🎨 style: add visual styles to RUC10 registration stepper

- src/main/java/com/sistema/gpon/controller/CuentaController.java
- src/main/resources/templates/cuenta/login.html
- src/main/resources/templates/fragments/layout.html
- src/main/resources/templates/planes/index.html
Refactored module names and texts to reflect the new system name Mobilnet. Minor spelling corrections included.
> ♻️ refactor(mobilnet): renamed system from 'Mobinet' to 'Mobilnet' and fixed typos

- src/main/java/com/sistema/gpon/controller/RegistroRUC10Controller.java
- src/main/resources/templates/registros/edicion.html
- src/main/resources/templates/registros/index.html
This PR fixes a bug where editing a record would create a new one instead of updating the existing entry.
Additionally, the "Export to Excel" button has been removed from the records index view.
> 🐛 fix(records): correctly update existing records and remove Excel button

- src/main/resources/static/css/index.css
- src/main/resources/templates/fragments/datatable-script.html
- Replaced default pagination arrows with up/down arrows for clearer sorting UI
- Set initial sort order descending on first column
> ✨ feat(datatable): add up and down arrows for sorting indicators

- src/main/java/com/sistema/gpon/controller/RegistroRUC10Controller.java
- src/main/java/com/sistema/gpon/service/EstadoRegistroService.java
- src/main/java/com/sistema/gpon/service/impl/ContactoPrincipalServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/ContactoSecundarioServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/CronogramaServiceImpl.java
- src/main/java/com/sistema/gpon/service/impl/EstadoRegistroServiceImpl.java
- Updated controller and service class names in the users module to follow consistent naming standards
- Improved method names to enhance readability and maintainability
- Cleaned up code formatting and removed redundant comments
- Ensured uniformity across the users module to facilitate future development and collaboration
> ♻️ refactor(records): rename controllers and services for better naming conventions and clarity
